package theoldone822.ArmorDamageRecalc;

import java.util.Arrays;

import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "ArmorDamageRecalc", name = "Armor Damage Recalc", version = "0.9b")
public class ArmorDamageRecalc {
	@Instance("ArmorDamageRecalc")
	public static ArmorDamageRecalc instance = new ArmorDamageRecalc();

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new EventHandlers());
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;

		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = ".";
	}
}
