package theoldone822.RoughStart;

import java.io.File;
import java.util.Arrays;

import theoldone822.RoughStart.CraftHandelers.*;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.crafting.CraftingManager;
import net.minecraft.item.Item;
import net.minecraft.item.ItemAxe;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.oredict.OreDictionary;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraftforge.oredict.ShapelessOreRecipe;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = "RoughStart", name = "Rough Start", version = "0.9b")
public class RoughStart {
	
	@Instance("RoughStart")
	public static RoughStart instance = new RoughStart();
	
	public static ToolMaterial toolCrude;
	public static ToolMaterial toolFlint;
	
	public static Item crudeAxe;
	public static Item flintAxe;
	public static Item leatherStrips;
	public static Item rock;
	public static Item kindling;
	public static Block stoneblock;
	
	public static boolean nerfPlank;
	public static boolean plankCut;
	public static boolean nerfStick;
	public static boolean stickCut;
	public static boolean nerfTorch;
	public static boolean nerfBlazePowder;
	public static boolean flintFurnace;
	public static boolean hardFurnace;
	public static boolean kindleFurnace;
	public static boolean smoothStoneTools;
	public static boolean rockRecipe;
	public static boolean naturalSticks;
	public static boolean naturalRocks;
	public static boolean noTreePunching;
	public static boolean enableCrudeAxe;
	public static boolean enableFlintAxe;
	public static boolean noWoolDrop;
	public static boolean enableleatherStrips;
	public static boolean moreLeather;
	public static boolean barkArmor;
	public static boolean simpleRepairsWood;
	public static boolean simpleRepairsStone;
	public static boolean simpleRepairsRock;
	public static boolean simpleRepairsCobble;
	public static boolean simpleRepairsLeather;
	public static boolean simpleRepairsLeatherStrip;
	public static boolean nerfBrewing;
	public static boolean throwingRock;
		
	public static int coalTorch;
	public static int charTorch;
	public static int blazeTorch;

	
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new EventHandlers());
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;
		
		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = ".";
		
		File installDir = event.getModConfigurationDirectory();
		Configuration settings = new Configuration(new File(installDir, "RoughStart.cfg"));
		
		settings.load();
		throwingRock = settings.get("Nerfs", "throwingRock", true).getBoolean();
		nerfPlank = settings.get("Nerfs", "Nerf Plank", true).getBoolean();
		plankCut = settings.get("Nerfs", "Plank Cutting", true, "add axe to recipe to get 4 planks").getBoolean();
		nerfStick = settings.get("Nerfs", "Nerf Stick", true).getBoolean();
		stickCut = settings.get("Nerfs", "Stick Cutting", true, "add axe to recipe to get 4 sticks").getBoolean();
		nerfTorch = settings.get("Tweaks", "Torch Tweak", true).getBoolean();
		nerfBlazePowder = settings.get("Nerfs", "Nerf Blaze Power", true).getBoolean();
		flintFurnace = settings.get("Nerfs", "Flint Furnace", true).getBoolean();
		hardFurnace = settings.get("Nerfs", "Hardcore Furnace", true, "Needs Flient and Steel in the middle. Get iron from zombie drop or chest.").getBoolean();
		smoothStoneTools = settings.get("Nerfs", "smoothStoneTools", true).getBoolean();
		blazeTorch = settings.get("Extras", "blazeTorch", 0).getInt();
		coalTorch = settings.get("Tweaks", "Coal Torch", 4).getInt();
		charTorch = settings.get("Tweaks", "Char Torch", 4).getInt();
		rockRecipe = settings.get("Extras", "rockRecipe", true).getBoolean();
		naturalSticks = settings.get("Extras", "naturalSticks", true).getBoolean();
		naturalRocks = settings.get("Extras", "naturalRocks", true).getBoolean();
		noTreePunching = settings.get("Nerfs", "noTreePunching", true).getBoolean();
		enableCrudeAxe = settings.get("Extras", "enableCrudeAxe", true).getBoolean();
		enableFlintAxe = settings.get("Extras", "enableFlintAxe", true).getBoolean();
		noWoolDrop = settings.get("Nerfs", "noWoolDrop", true).getBoolean();
//		enableleatherStrips = settings.get("Nerfs", "enableleatherStrips", true).getBoolean();
		nerfBrewing = settings.get("Nerfs", "Harder Brewing Stand", true).getBoolean();
		moreLeather = settings.get("Extras", "moreLeather", true).getBoolean();
//		barkArmor = settings.get("Nerfs", "barkArmor", true).getBoolean();
		simpleRepairsWood = settings.get("Extras", "simpleRepairsWood", true).getBoolean();
		simpleRepairsStone = settings.get("Extras", "simpleRepairsStone", true).getBoolean();
		simpleRepairsCobble = settings.get("Extras", "simpleRepairsCobble", true).getBoolean();
		simpleRepairsRock = settings.get("Extras", "simpleRepairsRock", true).getBoolean();
		simpleRepairsLeather = settings.get("Extras", "simpleRepairsLeather", true).getBoolean();
		simpleRepairsLeatherStrip = settings.get("Extras", "simpleRepairsLeatherStrip", false).getBoolean();

		settings.save();
		
		
		toolCrude = EnumHelper.addToolMaterial("Crude", 0, 32, 1.5F, -1.0F, 15);
		
		toolFlint = EnumHelper.addToolMaterial("Flint", 0, 122, 3.5F, 0.5F, 5);
		
		FMLCommonHandler.instance().bus().register(new CraftHandeler());
	}
	
	@EventHandler
	public void InitiateRoughStart(FMLInitializationEvent initEvent) {
		instance = this;
		
		Blocks.log.setHarvestLevel("axe", 0);
		Blocks.log2.setHarvestLevel("axe", 0);
		
		crudeAxe = new BasicAxe(toolCrude).setUnlocalizedName("crudeAxe").setTextureName("roughstart:crudeAxe");
		flintAxe = new BasicAxe(toolFlint).setUnlocalizedName("flintAxe").setTextureName("roughstart:flintAxe");
		
		leatherStrips = new BasicItem().setUnlocalizedName("leatherStrips").setTextureName("roughstart:leatherStrips");
		rock = new BasicItem().setUnlocalizedName("rock").setTextureName("roughstart:rock");
		kindling = new BasicItem().setUnlocalizedName("kindling").setTextureName("roughstart:kindling");
		stoneblock = new BasicBlock(Material.ground).setBlockName("stoneblock").setBlockTextureName("roughstart:stoneblock");

		if (enableCrudeAxe)
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(crudeAxe), true, new Object[] { "XY", " Y", Character.valueOf('X'), new ItemStack(rock), Character.valueOf('Y'), "stickWood"}));
		if (enableFlintAxe){
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(flintAxe), true, new Object[] { "XY", " Y", Character.valueOf('X'), new ItemStack(Items.flint), Character.valueOf('Y'), "stickWood"}));
        GameRegistry.addRecipe(new EasyRepairFlintTools());
		}
	
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
        if(flintFurnace || hardFurnace || kindleFurnace)
		RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.furnace));
		
        if(flintFurnace)
        CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(Blocks.furnace, true, new Object[] { "XXX", "XYX", "XXX", Character.valueOf('X'), Blocks.cobblestone, Character.valueOf('Y'), Items.flint }));
		
        if(hardFurnace)
            CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(Blocks.furnace, true, new Object[] { "XXX", "XYX", "XXX", Character.valueOf('X'), Blocks.cobblestone, Character.valueOf('Y'), Items.flint_and_steel }));

        if(kindleFurnace)
            CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(Blocks.furnace, true, new Object[] { "XXX", "XYX", "XXX", Character.valueOf('X'), Blocks.cobblestone, Character.valueOf('Y'), kindling }));

        if (nerfPlank){
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.planks, 4, 0));
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.planks, 4, 1));
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.planks, 4, 2));
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.planks, 4, 3));
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.planks, 4, 4));
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.planks, 4, 5));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.planks, 2), true, new Object[] { "X", Character.valueOf('X'), new ItemStack(Blocks.log, 1, 0)}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.planks, 2, 1), true, new Object[] { "X", Character.valueOf('X'), new ItemStack(Blocks.log, 1, 1)}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.planks, 2, 2), true, new Object[] { "X", Character.valueOf('X'), new ItemStack(Blocks.log, 1, 2)}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.planks, 2, 3), true, new Object[] { "X", Character.valueOf('X'), new ItemStack(Blocks.log, 1, 3)}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.planks, 2, 4), true, new Object[] { "X", Character.valueOf('X'), new ItemStack(Blocks.log2, 1)}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.planks, 2, 5), true, new Object[] { "X", Character.valueOf('X'), new ItemStack(Blocks.log2, 1, 1)}));
		}
        
		if (nerfTorch){
        RecipeRemover.removeAnyRecipe(new ItemStack(Blocks.torch, 4));
		if (coalTorch > 0)
			CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.torch, coalTorch), true, new Object[] { "X", "Y", Character.valueOf('X'), new ItemStack(Items.coal, 1, 0), Character.valueOf('Y'), "stickWood"}));

		if (charTorch > 0)
			CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.torch, charTorch), true, new Object[] { "X", "Y", Character.valueOf('X'), new ItemStack(Items.coal, 1, 1), Character.valueOf('Y'), "stickWood"}));
		}

		if (blazeTorch > 0){
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.torch, blazeTorch), true, new Object[] { "X", "Y", Character.valueOf('X'), Items.blaze_powder, Character.valueOf('Y'), "stickWood"}));
		}
		
		if (nerfBlazePowder){
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.blaze_powder, 2));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(Items.blaze_powder, true, new Object[] { "X", Character.valueOf('X'), Items.blaze_rod }));
		}
		
		if (nerfStick){
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.stick, 4));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stick, 2), true, new Object[] { "X", "X", Character.valueOf('X'), "plankWood"}));
		}
		
		if (nerfBrewing){
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.brewing_stand));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.brewing_stand), true, new Object[] { "IXI", " X ", "ZZZ", Character.valueOf('X'), Items.blaze_rod, Character.valueOf('Y'), Items.iron_ingot, Character.valueOf('Z'), Blocks.stone}));
		}
		
		if (smoothStoneTools){
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.stone_axe));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.stone_hoe));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.stone_pickaxe));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.stone_sword));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.stone_shovel));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stone_axe), true, new Object[] { "YY ", "YX ", " X ", Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.stone}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stone_pickaxe), true, new Object[] { "YYY", " X ", " X ", Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.stone}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stone_hoe), true, new Object[] { "YY ", " X ", " X ", Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.stone}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stone_shovel), true, new Object[] { " Y ", " X ", " X ", Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.stone}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stone_sword), true, new Object[] { " Y ", " Y ", " X ", Character.valueOf('X'), "stickWood", Character.valueOf('Y'), Blocks.stone}));
		}
		
		if (simpleRepairsRock){
	        GameRegistry.addRecipe(new EasyRepairStoneToolsRock());
		}
		
		if (simpleRepairsCobble){
	        GameRegistry.addRecipe(new EasyRepairCobbleTools());
		}
		
		if (simpleRepairsStone){
	        GameRegistry.addRecipe(new RepairStoneTools());
		}
		
		if (simpleRepairsWood){
	        GameRegistry.addRecipe(new EasyRepairWoodTools());
		}
		
		if (simpleRepairsLeather){
	        GameRegistry.addRecipe(new EasyRepairLeather());
		}
		
		if (naturalRocks){
			CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(rock), new Object[] {Blocks.cobblestone}));
	        MinecraftForge.addGrassSeed(new ItemStack(rock, 1, 0), 1);
		}
		
		if (naturalSticks){
        MinecraftForge.addGrassSeed(new ItemStack(Items.stick, 1, 0), 2);
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Items.stick), new Object[] {"treeSapling"}));
		}

		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Blocks.cobblestone), true, new Object[] { "XX", "XX", Character.valueOf('X'), rock}));
		
		for(int i = 0; i < 32000; i ++){
			if(Item.getItemById(i) != null){
                if(Item.getItemById(i) instanceof ItemAxe) {
            		OreDictionary.registerOre("toolAxe", new ItemStack(Item.getItemById(i), 1, OreDictionary.WILDCARD_VALUE));
                }
			}
		}
		
		for(int i = 0; i < 32000; i ++){
			if(Item.getItemById(i) != null){
                if(Item.getItemById(i) instanceof ItemPickaxe) {
            		OreDictionary.registerOre("toolPickaxe", new ItemStack(Item.getItemById(i), 1, OreDictionary.WILDCARD_VALUE));
                }
			}
		}
		
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.leather_boots));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.leather_chestplate));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.leather_helmet));
        RecipeRemover.removeAnyRecipe(new ItemStack(Items.leather_leggings));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.leather_boots), new Object[] {"X X", "X X", Character.valueOf('X'), leatherStrips}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.leather_chestplate), new Object[] {"X X", "XXX", "XXX", Character.valueOf('X'), leatherStrips}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.leather_helmet), new Object[] {"XXX", "X X", Character.valueOf('X'), leatherStrips}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.leather_leggings), new Object[] {"XXX", "X X", "X X", Character.valueOf('X'), leatherStrips}));
		
		if (simpleRepairsLeatherStrip){
	        GameRegistry.addRecipe(new EasyRepairLeatherStrip());
		}

		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(leatherStrips, 3, 0), new Object[] {Items.leather}));
		
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Items.leather, 1, 0), new Object[] {leatherStrips, leatherStrips, leatherStrips}));

		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(kindling, 1, 0), new Object[] {Blocks.cobblestone, "stickWood", "stickWood", "stickWood", "stickWood", "stickWood", Items.flint}));
		
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(kindling, 1, 0), new Object[] {rock, "stickWood", "stickWood", "stickWood", "stickWood", "stickWood", Items.flint}));
		
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(rock, 2, 0), new Object[] {Blocks.cobblestone, "toolPickaxe"}));
		
        if (nerfStick && stickCut)
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(new ItemStack(Items.stick, 4), true, new Object[] { "YX", " X", Character.valueOf('X'), "plankWood", Character.valueOf('Y'), "toolAxe"}));
		
        if (nerfPlank && plankCut){
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Blocks.planks, 4, 0), new Object[] {new ItemStack(Blocks.log, 1, 0), "toolAxe"}));
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Blocks.planks, 4, 1), new Object[] {new ItemStack(Blocks.log, 1, 1), "toolAxe"}));
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Blocks.planks, 4, 2), new Object[] {new ItemStack(Blocks.log, 1, 2), "toolAxe"}));
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Blocks.planks, 4, 3), new Object[] {new ItemStack(Blocks.log, 1, 3), "toolAxe"}));
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Blocks.planks, 4, 4), new Object[] {new ItemStack(Blocks.log2, 1, 0), "toolAxe"}));
		CraftingManager.getInstance().getRecipeList().add(new ShapelessOreRecipe(new ItemStack(Blocks.planks, 4, 5), new Object[] {new ItemStack(Blocks.log2, 1, 1), "toolAxe"}));
        }
	}
}
