package theoldone822.EWzoomfix;

import java.util.Arrays;

import theoldone822.EWzoomfix.CommonProxy;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@NetworkMod(clientSideRequired = true, serverSideRequired = false)
@Mod(
		modid = "ewzoomfix",
		name = "Extended Work Zoom Fix",
		version = "1.0",
		dependencies = "required-after:extendedWorkbench")

public class EWzoomfix {
	@SidedProxy(clientSide = "theoldone822.EWzoomfix.ClientProxy",
			serverSide = "theoldone822.EWzoomfix.CommonProxy")
	public static CommonProxy proxy;

	@Instance("EWzoomfix")
	public static EWzoomfix instance;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		proxy.registerClientTickHandler();
		proxy.preInit();
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;

		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = "Adds zoom to the Extended bow.";
	}
}
