package theoldone822.woolarmor;

import java.util.Arrays;

import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.crafting.CraftingManager;
import net.minecraft.item.ItemArmor;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "woolarmor", name = "Wool Armor", version = "1.3")
public class Woolarmor {

	public static ArmorMaterial armorWool;
	public static Item woolHelm;
	public static Item woolChest;
	public static Item woolLegs;
	public static Item woolBoots;
	public static Item extendedwoolHelm;
	public static Item extendedwoolChest;
	public static Item extendedwoolLegs;
	public static Item extendedwoolBoots;

	@SidedProxy(clientSide = "theoldone822.woolarmor.ClientProxy", serverSide = "theoldone822.woolarmor.CommonProxy")
	public static CommonProxy proxy;

	@Instance("woolarmor")
	public static Woolarmor instance;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		proxy.preInit();
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;

		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = "Adds wool armor.";


		armorWool = EnumHelper.addArmorMaterial("WOOL", 3, new int[] { 1, 2, 1, 1 }, 8);
		woolHelm = new ItemArmor(armorWool, 0, 0).setUnlocalizedName("woolarmors:woolHelmet").setTextureName("WoolArmors:WoolHelmet");
		woolChest = new ItemArmor(armorWool, 0, 1).setUnlocalizedName("woolarmors:woolChestplate").setTextureName("WoolArmors:WoolChestplate");
		woolLegs = new ItemArmor(armorWool, 0, 2).setUnlocalizedName("woolarmors:woolLeggings").setTextureName("WoolArmors:WoolLeggings");
		woolBoots = new ItemArmor(armorWool, 0, 3).setUnlocalizedName("woolarmors:woolBoots").setTextureName("WoolArmors:WoolBoots");

		LanguageRegistry.addName(woolHelm, "Wool Helmet");
		LanguageRegistry.addName(woolChest, "Wool Chestplate");
		LanguageRegistry.addName(woolLegs, "Wool Leggings");
		LanguageRegistry.addName(woolBoots, "Wool Boots");
		
		GameRegistry.registerItem(woolHelm, "WoolHelmet");
		GameRegistry.registerItem(woolChest, "WoolChestplate");
		GameRegistry.registerItem(woolLegs, "WoolLeggings");
		GameRegistry.registerItem(woolBoots, "WoolBoots");
		
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(woolHelm, true, new Object[] { "XXX", "X X", Character.valueOf('X'), Blocks.wool }));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(woolChest, true, new Object[] { "X X", "XXX", "XXX", Character.valueOf('X'), Blocks.wool }));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(woolLegs, true, new Object[] { "XXX", "X X", "X X", Character.valueOf('X'), Blocks.wool }));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(woolBoots, true, new Object[] { "X X", "X X", Character.valueOf('X'), Blocks.wool }));
	}
}
