package theoldone822.MoreFusionFurnaces;

import java.io.File;
import java.util.Arrays;

import alexndr.SimpleOres.api.helpers.CoreHelper;
import alexndr.SimpleOres.plugins.fusion.FusionHelper;
import theoldone822.MoreFusionFurnaces.Furnaces.MythrilFusionFurnace;
import theoldone822.MoreFusionFurnaces.Furnaces.MythrilFusionFurnaceTileEntity;
import theoldone822.MoreFusionFurnaces.Furnaces.OnyxFusionFurnace;
import theoldone822.MoreFusionFurnaces.Furnaces.OnyxFusionFurnaceTileEntity;
import net.minecraft.block.Block;
import net.minecraft.item.crafting.CraftingManager;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.oredict.ShapedOreRecipe;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid = "morefusionfurnaces", name = "More Fusion Furnaces", version = "2.0", dependencies = "required-after:simpleores; required-after:simpleoresfusion")
public class MoreFusionFurnaces {
	@SidedProxy(clientSide = "theoldone822.MoreFusionFurnaces.ProxyClient", serverSide = "theoldone822.MoreFusionFurnaces.ProxyCommon")	
	public static ProxyCommon proxy;

	public static Block mythrilFusionFurnace;
	public static Block mythrilFusionFurnaceOn;
	public static Block onyxFusionFurnace;
	public static Block onyxFusionFurnaceOn;

	public static Configuration config;
	public static int mythrilFurnaceMultiplier, onyxFurnaceMultiplier, onyxFurnaceMultiChance;

	@Instance("MoreFusionFurnaces")
	public static MoreFusionFurnaces instance = new MoreFusionFurnaces();

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;

		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = "Adds Mithril and Onyx Fusion Furnaces.";
		config = new Configuration(event.getSuggestedConfigurationFile());
		config.load();

		//Custom Furnace Multipliers
    	mythrilFurnaceMultiplier = config.get("Multiplier", "Mythril Furnace Fuel Length Multiplier", 2).getInt();
    	onyxFurnaceMultiplier = config.get("Multiplier", "Onyx Furnace Extra Yield Amount", 1).getInt();
    	onyxFurnaceMultiChance = config.get("Multiplier", "Onyx Furnace Multi Yield Chance (From 1 to 100)", 33).getInt();
		
		mythrilFusionFurnace = new MythrilFusionFurnace(false).setHardness(CoreHelper.coreSettings.mythrilFurnaceHardness).setResistance(CoreHelper.coreSettings.mythrilFurnaceResistance).setBlockName("morefusionfurnaces:mythrilFusionFurnace");
		mythrilFusionFurnaceOn = new MythrilFusionFurnace(true).setHardness(CoreHelper.coreSettings.mythrilFurnaceHardness).setResistance(CoreHelper.coreSettings.mythrilFurnaceResistance).setLightLevel(CoreHelper.coreSettings.mythrilFurnaceLightValue).setBlockName("morefusionfurnaces:mythrilFusionFurnaceOn");
		onyxFusionFurnace = new OnyxFusionFurnace(false).setHardness(CoreHelper.coreSettings.onyxFurnaceHardness).setResistance(CoreHelper.coreSettings.onyxFurnaceResistance).setBlockName("morefusionfurnaces:onyxFusionFurnace");
		onyxFusionFurnaceOn = new OnyxFusionFurnace(true).setHardness(CoreHelper.coreSettings.onyxFurnaceHardness).setResistance(CoreHelper.coreSettings.onyxFurnaceResistance).setLightLevel(CoreHelper.coreSettings.onyxFurnaceLightValue).setBlockName("morefusionfurnaces:onyxFusionFurnaceOn");

		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(mythrilFusionFurnace, true, new Object[]{
				"XXX", "XYX", "XXX", Character.valueOf('X'), "ingotMythril", Character.valueOf('Y'), FusionHelper.fusionContent.fusion_furnace}));
		CraftingManager.getInstance().getRecipeList().add(new ShapedOreRecipe(onyxFusionFurnace, true, new Object[]{
				"XXX", "XYX", "XXX", Character.valueOf('X'), "gemOnyx", Character.valueOf('Y'), FusionHelper.fusionContent.fusion_furnace}));
		
		GameRegistry.registerBlock(mythrilFusionFurnace, "mythrilFusionFurnace");
		GameRegistry.registerBlock(mythrilFusionFurnaceOn, "mythrilFusionFurnaceOn");
		GameRegistry.registerBlock(onyxFusionFurnace, "onyxFusionFurnace");
		GameRegistry.registerBlock(onyxFusionFurnaceOn, "onyxFusionFurnaceOn");

		LanguageRegistry.addName(mythrilFusionFurnace, "Mythril Fusion Furnace");
		LanguageRegistry.addName(mythrilFusionFurnaceOn, "Mythril Fusion Furnace");
		LanguageRegistry.addName(onyxFusionFurnace, "Onyx Fusion Furnace");
		LanguageRegistry.addName(onyxFusionFurnaceOn, "Onyx Fusion Furnace");

	}

	@EventHandler
	public void InitiateMoreFusionFurnaces(FMLInitializationEvent initEvent) {
		instance = this;
		NetworkRegistry.INSTANCE.registerGuiHandler(instance, proxy);
		GameRegistry.registerTileEntity(MythrilFusionFurnaceTileEntity.class, "mythrilFusionFurnace");
		GameRegistry.registerTileEntity(OnyxFusionFurnaceTileEntity.class, "onyxFusionFurnace");

		config.save();
	}

}
