package theoldone822.ashenwheatMFR;

import java.util.Arrays;

import akkamaddi.ashenwheat.code.AshenWheatCore;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import powercrystals.minefactoryreloaded.MFRRegistry;
import powercrystals.minefactoryreloaded.farmables.fertilizables.FertilizableCropPlant;
import powercrystals.minefactoryreloaded.farmables.harvestables.HarvestableCropPlant;
import powercrystals.minefactoryreloaded.farmables.plantables.PlantableCropPlant;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLInterModComms;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@NetworkMod(clientSideRequired = true, serverSideRequired = false)
@Mod(modid = "ashenwheatmfr", name = "MFR support for Ashenwheat", version = "1.0", dependencies = "required-after:MineFactoryReloaded; required-after:ashenwheat")
public class AshenwheatMFR {
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;

		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = "Forestry and MFR support for Ashenwheat.";
	}

	@EventHandler
	public void Load(FMLInitializationEvent initEvent){
		if (Loader.isModLoaded("MineFactoryReloaded")) {
			MFRRegistry.registerPlantable(new PlantableCropPlant(AshenWheatCore.ashSeeds.itemID, AshenWheatCore.ashWheatCrop.blockID));
		
			MFRRegistry.registerPlantable(new PlantableCropPlant(AshenWheatCore.scintillaSeeds.itemID, AshenWheatCore.scintillaWheatCrop.blockID));
			MFRRegistry.registerPlantable(new PlantableCropPlant(AshenWheatCore.ossidSeeds.itemID, AshenWheatCore.ossidRootCrop.blockID));
			MFRRegistry.registerPlantable(new PlantableCropPlant(AshenWheatCore.thunderSeeds.itemID, AshenWheatCore.thunderGrassCrop.blockID));

			MFRRegistry.registerHarvestable(new HarvestableCropPlant(AshenWheatCore.ashWheatCrop.blockID, 7));
			MFRRegistry.registerHarvestable(new HarvestableCropPlant(AshenWheatCore.scintillaWheatCrop.blockID, 7));
			MFRRegistry.registerHarvestable(new HarvestableCropPlant(AshenWheatCore.ossidRootCrop.blockID, 7));
			MFRRegistry.registerHarvestable(new HarvestableCropPlant(AshenWheatCore.thunderGrassCrop.blockID, 7));

			MFRRegistry.registerFertilizable(new FertilizableCropPlant(AshenWheatCore.ashWheatCrop.blockID, 7));
			MFRRegistry.registerFertilizable(new FertilizableCropPlant(AshenWheatCore.scintillaWheatCrop.blockID, 7));
			MFRRegistry.registerFertilizable(new FertilizableCropPlant(AshenWheatCore.ossidRootCrop.blockID, 7));
			MFRRegistry.registerFertilizable(new FertilizableCropPlant(AshenWheatCore.thunderGrassCrop.blockID, 7));
		}
		
        FMLInterModComms.sendMessage("Forestry", "add-farmable-crop", "farmWheat@" + AshenWheatCore.ashSeeds.itemID + ".0." + AshenWheatCore.ashWheatCrop.blockID + ".7");
        FMLInterModComms.sendMessage("Forestry", "add-farmable-crop", "farmWheat@" + AshenWheatCore.thunderSeeds.itemID + ".0." + AshenWheatCore.thunderGrassCrop.blockID + ".7");
        FMLInterModComms.sendMessage("Forestry", "add-farmable-crop", "farmWheat@" + AshenWheatCore.ossidSeeds.itemID + ".0." + AshenWheatCore.ossidRootCrop.blockID + ".7");
        FMLInterModComms.sendMessage("Forestry", "add-farmable-crop", "farmWheat@" + AshenWheatCore.scintillaSeeds.itemID + ".0." + AshenWheatCore.scintillaWheatCrop.blockID + ".7");
	}
}
